apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: launchboard-secret
  namespace: devops-launchboard
spec:
  encryptedData:
    POSTGRES_PASSWORD: REPLACE_WITH_KUBESEAL_OUTPUT
    DATABASE_URL: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: launchboard-secret
      namespace: devops-launchboard
    type: Opaque
