apiVersion: v1
kind: LimitRange
metadata:
  name: launchboard-default-limits
  namespace: devops-launchboard
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      max:
        cpu: "2"
        memory: 2Gi
      min:
        cpu: 25m
        memory: 64Mi
