server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: gp3-encrypted
  auditStorage:
    enabled: true
    size: 5Gi
    storageClass: gp3-encrypted
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
ui:
  enabled: true
  serviceType: ClusterIP
injector:
  enabled: true
