apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-admin
  namespace: devops-launchboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: litmus-pod-chaos
  namespace: devops-launchboard
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-pod-chaos
  namespace: devops-launchboard
subjects:
  - kind: ServiceAccount
    name: litmus-admin
    namespace: devops-launchboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: litmus-pod-chaos
