apiVersion: apps/v1
kind: Deployment
metadata: {name: launchboard-backend-green, namespace: devops-launchboard}
spec:
  replicas: 2
  strategy: {type: RollingUpdate, rollingUpdate: {maxSurge: 1, maxUnavailable: 0}}
  selector: {matchLabels: {app: launchboard-backend, track: green}}
  template:
    metadata: {labels: {app: launchboard-backend, track: green}}
    spec:
      containers:
        - name: backend
          image: "[AWS_ACCOUNT_ID].dkr.ecr.[REGION].amazonaws.com/launchboard-backend:[IMAGE_TAG]"
          imagePullPolicy: IfNotPresent
          ports: [{containerPort: 8000}]
          readinessProbe: {httpGet: {path: /ready, port: 8000}, initialDelaySeconds: 10, periodSeconds: 10}
          livenessProbe: {httpGet: {path: /health, port: 8000}, initialDelaySeconds: 20, periodSeconds: 15}
          resources: {requests: {cpu: 100m, memory: 128Mi}, limits: {cpu: 500m, memory: 512Mi}}
