apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: launchboard-backend-pod-delete
  namespace: devops-launchboard
spec:
  appinfo:
    appns: devops-launchboard
    applabel: app=launchboard-backend
    appkind: deployment
  chaosServiceAccount: litmus-admin
  engineState: active
  annotationCheck: "false"
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: FORCE
              value: "false"
