apiVersion: velero.io/v1
kind: Restore
metadata:
  name: launchboard-manual-restore
  namespace: velero
spec:
  backupName: launchboard-manual-dr
  includedNamespaces:
    - devops-launchboard
  existingResourcePolicy: update
