apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata: {name: launchboard-secret, namespace: devops-launchboard}
spec: {encryptedData: {POSTGRES_PASSWORD: AgByEncryptedTrainingValueReplaceWithKubesealOutput}}
