apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-launchboard-dev

resources:
  - ../../app-k8s

patches:
  - target:
      kind: Deployment
      name: launchboard-backend
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: launchboard-backend
      spec:
        replicas: 1
  - target:
      kind: Deployment
      name: launchboard-frontend
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: launchboard-frontend
      spec:
        replicas: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: launchboard-backend
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: launchboard-backend
      spec:
        minReplicas: 1
        maxReplicas: 2
  - target:
      kind: Ingress
      name: launchboard-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: launchboard-ingress
        annotations:
          alb.ingress.kubernetes.io/load-balancer-name: launchboard-phase-13-dev
