apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-launchboard

resources:
  - ../../app-k8s

patches:
  - target:
      kind: Deployment
      name: launchboard-backend
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: launchboard-backend
      spec:
        replicas: 3
  - target:
      kind: ConfigMap
      name: launchboard-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: launchboard-config
      data:
        SEED_DEMO_DATA: "false"
  - target:
      kind: HorizontalPodAutoscaler
      name: launchboard-backend
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: launchboard-backend
      spec:
        minReplicas: 3
        maxReplicas: 8
